import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";
import type { ReactElement } from "react";

const styles = StyleSheet.create({
  page: { padding: 40, fontSize: 11, fontFamily: "Helvetica", color: "#111" },
  brand: { fontSize: 18, fontWeight: 700, color: "#16a34a", marginBottom: 12 },
  h1: { fontSize: 14, fontWeight: 700, marginTop: 14, marginBottom: 6 },
  kpi: { flexDirection: "row", gap: 12, marginTop: 8 },
  kpiBox: { flex: 1, border: "1px solid #e5e7eb", borderRadius: 6, padding: 12 },
  kpiLabel: { color: "#666", fontSize: 9, marginBottom: 4 },
  kpiValue: { fontSize: 18, fontWeight: 700 },
  p: { lineHeight: 1.5 },
  footer: { marginTop: 24, color: "#999", fontSize: 9, textAlign: "center" },
});

export function WeeklyReportPdf({
  client,
  weekStart,
  adherence,
  points,
  summary,
}: {
  client: { name: string };
  weekStart: string;
  adherence: number;
  points: number;
  summary: string;
}): ReactElement {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={styles.brand}>FitCoachAI — Weekly progress</Text>
        <Text>{client.name} · week of {new Date(weekStart).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" })}</Text>

        <View style={styles.kpi}>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Adherence</Text>
            <Text style={styles.kpiValue}>{adherence}%</Text>
          </View>
          <View style={styles.kpiBox}>
            <Text style={styles.kpiLabel}>Points</Text>
            <Text style={styles.kpiValue}>{points}</Text>
          </View>
        </View>

        <Text style={styles.h1}>Summary</Text>
        <Text style={styles.p}>{summary}</Text>

        <Text style={styles.footer}>Generated by FitCoachAI</Text>
      </Page>
    </Document>
  );
}
