import Link from "next/link";
import { Dumbbell } from "lucide-react";

export const metadata = { title: "Terms of Service" };

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <header className="sticky top-0 z-20 border-b bg-background/70 backdrop-blur-md">
        <div className="container flex h-14 items-center justify-between">
          <Link href="/" className="flex items-center gap-2 font-bold">
            <div className="flex h-7 w-7 items-center justify-center rounded-md bg-gradient-to-br from-brand-500 to-emerald-500">
              <Dumbbell className="h-4 w-4 text-white" />
            </div>
            FitCoachAI
          </Link>
        </div>
      </header>

      <article className="container max-w-3xl space-y-6 py-12 text-sm leading-relaxed">
        <h1 className="text-3xl font-bold">Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString("en-IN", { day: "2-digit", month: "long", year: "numeric" })}</p>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold">1. Service</h2>
          <p>
            FitCoachAI is a software platform that helps gyms manage trainers, clients, AI-generated plans, billing, and
            communications. Your gym&apos;s owner is your point of contact for membership, payments, and personal
            training. FitCoachAI is the technology provider.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold">2. AI disclaimer</h2>
          <p>
            Plans generated by the AI are <strong>suggestions</strong>, not medical advice. Always consult a qualified
            doctor or registered dietitian before starting a new training program, dietary regime, or treating any
            condition. If you have a severe medical condition, are pregnant, recovering from surgery, or under 18, get
            clearance from your physician first.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold">3. Acceptable use</h2>
          <ul className="list-disc space-y-1 pl-6">
            <li>Don&apos;t share your password or sign in as someone else.</li>
            <li>Don&apos;t send abusive content via chat, broadcasts, or announcements.</li>
            <li>Don&apos;t attempt to bypass plan limits or scrape AI responses for resale.</li>
            <li>Don&apos;t upload illegal or copyrighted material to progress photos / chat.</li>
          </ul>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold">4. Billing</h2>
          <p>
            Membership pricing, refund policy, and cancellation rules are set by your individual gym. Invoices issued
            through FitCoachAI are records of a transaction between you and your gym. Disputes about charges should be
            raised with the gym owner; FitCoachAI cannot reverse them on your behalf.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold">5. Liability</h2>
          <p>
            FitCoachAI is provided &ldquo;as is&rdquo; without warranty of fitness for a particular purpose. We are not
            liable for injuries sustained while following AI-generated or trainer-prescribed plans. Use your judgement,
            warm up properly, and stop if anything hurts.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold">6. Termination</h2>
          <p>
            You can deactivate your account by asking your gym owner. The owner can deactivate accounts that violate
            these terms. Deactivation removes login access; full data deletion happens 30 days later unless an active
            invoice dispute is pending.
          </p>
        </section>

        <section className="space-y-2">
          <h2 className="text-xl font-semibold">7. Changes</h2>
          <p>
            We may update these terms occasionally. If material changes apply to existing users, you&apos;ll see an in-app
            announcement at least 14 days before the change takes effect.
          </p>
        </section>

        <hr className="my-8" />
        <p className="text-xs text-muted-foreground">
          Baseline template — adapt jurisdictionally before public release.
        </p>
      </article>
    </div>
  );
}
